dna = "TTGATGGAGCCGGGCCACGACAAACATAACTGGCCGGCCTTACCCAGCGTATGCACTATGTTCTAGGGGGACACTGACTCTGGTCGGAACAAAACTCGGATACTCCTTGGAGGCAGCGCGCCTGTAGTGTTCGGACCTCAAAGGAGTCCCCTAGGCGATTTAATTCTGTGCTTCACCAGGACCGGGTAGTCGACTCATTAGCACTATGAAGTGTAGGATGCACATAATCGACGGACGAGTCATTGATACCTGAAGCCCACACTAGGGGTACACCCTTCAAATAAACTGGGTGCAACTCTAATACCCGGTTGGCGAAACGCCGCGGAATAGTGACGCCGTACTCGCCTCGGAACGCGCCAAGTCCTTCACCCAGTGCCTGATGCTCGTAATAGCTTGGTAATTGGCGGGCGGGTGGGTGATAAAGGGTTCGTCGCGGAAGGATAGGTATTCCCATGTTGGGACTCTTAACTATTTGTCACTAAATCACCGTTACGGGGCAACCGCATAAAACCGTGGTATAAAGACCCGGTCTATAGTCTCCTAAGGCCCTTGGGCTCTACGCTCCAATAGCACAAATTGGAGACCCCCCTGTCTACACTTTTATAACAAAAAAGCCCGATGTAGTAACCTGCCGCAGACGTCAAGGTCTATCGGGGCGGACGTGTTTGCGGCGATGACGACCCGGGGAAAGGACCCCAACCGCCGTCTACCGCGGTGTGACGTAATACGACCTAAGTTTGCGATCAGGCGGTCTTTGGCGTGGCCCTCTTGTGCTTCAGCTATTTCAACGGGCTGCAGTGGCGTGGCGACAACTCACATA"
a_ct = 0
c_ct = 0
t_ct = 0
g_ct = 0

for nuc in dna: 
    if nuc == "A":
        a_ct += 1
    elif nuc == "C":
        c_ct += 1
    elif nuc == "G":
        g_ct += 1
    else:
        t_ct += 1
    

print(a_ct, c_ct, g_ct, t_ct)

